modules/admin/models/Users.php
<?php

namespace app\modules\admin\models;

use yii\db\ActiveRecord;

class Users extends ActiveRecord
{
    public static function tableName()
    {
        return 'users';
    }
}

modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use yii\web\Controller;

use app\modules\admin\components\AController;
/**
 * Default controller for the `admin` module
 */
class DefaultController extends AController
{
    /**
     * Renders the index view for the module
     * @return string
     */
   
    public function actionIndex()
    {
        return $this->render('index');
    }

}

modules/admin/controllers/TasksController.php
<?php

namespace app\modules\admin\controllers;

use app\modules\admin\components\AController;
use app\models\ToDoList;
use Yii;
use yii\web\Response;

class TasksController extends AController
{
	public function actionIndex()
    {
    	$tasks = ToDoList::find()->all();
    	return $this->render('index',[
    		'tasks' => $tasks
    	]);
    } 

    public function actionEdit()
	{
		$request = Yii::$app->request;
        if($request->post('id')){
            $model = ToDoList::findOne($request->post('id'));
        }
        if (Yii::$app->request->isAjax) {
            $model->text = $request->post('text');

            $model->status = $request->post('status');
            $model->save();
          
            $data = [
                'id' => $model->id,
                'text' => $model->text,
                'status' => [
                	'code' => $model->status,
                	'text' => $model->getStatusText()
                ]
            ];
        }

        Yii::$app->response->format = Response::FORMAT_JSON;

        return $data;
	}  

	public function actionDelete($id)
	{
		  $model = ToDoList::findOne($id);

		  $model->delete();

		  return $this->redirect('/admin/tasks');
	}
}

modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\modules\admin\components\AController;

use app\modules\admin\models\Users;

class UsersController extends AController
{
   	  public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }


   	public function actions()
   	{
   		return [
   			'error' => [
   				'class' => 'yii\web\ErrorAction',
   			],
   			'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
   		];
   	}

    public function actionIndex()
    {
    	$users = Users::find()->all();
     	return $this->render('index',[
     		'users' => $users
     	]);
    }
}

modules/admin/views/default/index.php
<div class="test-default-index">
    <h1><?= $this->context->action->uniqueId ?></h1>
    <p>
        This is the view content for action "<?= $this->context->action->id ?>".
        The action belongs to the controller "<?= get_class($this->context) ?>"
        in the "<?= $this->context->module->id ?>" module.
    </p>
    <p>
        You may customize this page by editing the following file:<br>
        <code><?= __FILE__ ?></code>
    </p>
</div>

modules/admin/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Users', 'url' => ['/admin/users']],

            ['label' => 'Tasks', 'url' => ['/admin/tasks']],
            
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/tasks/index.php
<?php

use yii\helpers\Html;
?>
 
<diV class="col-md-12">
	<table class="table table-bordered">
		<caption>Tasks</caption>
		<thead>
			<tr>
				<th>Id</th>
				<th>User</th>
				<th>Text</th>
				<th>Status</th>
				<th class="text-right">Control</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($tasks as $task): ?>
			<tr>
				<td><?= $task->id ?></td>
				<td><?= $task->user->name ?></td>
				<td id="text-<?= $task->id ?>"><?= $task->text ?></td>
				<td id="status-<?= $task->id?>"><?= $task->getStatusText() ?></td>
				<td class="text-right" width="15%">
					<a class="btn btn-info edit" data-id="<?= $task->id ?>" data-status="<?= $task->status ?>">Edit</a>
					<?= Html::a('Delete',['tasks/delete', 'id' => $task->id], ['class'=>'btn btn-danger']);?>
					
				</td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</diV>

<a class="btn-modal" style="display:none" data-toggle="modal" data-target="#exampleModal"></a>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tahrirlash</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<input type="hidden" id="id-modal-input" value="">
      	<textarea name="text" class="form-control" id="text-modal-textarea"></textarea><br>
      	<select name="" id="task-status-select" class="form-control">
      		<option value="1">New</option>
      		<option value="2">To Do</option>
      		<option value="3">Done</option>
      	</select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Yopish</button>
        <button type="button" class="btn btn-primary save">Saqlash</button>
      </div>
    </div>
  </div>
</div>

<?php
$js = <<< JS
	$('.edit').on('click',function(){
		$('#id-modal-input').val($(this).attr('data-id'));
		let text = $('#text-'+$(this).attr('data-id')).text();
		$('#text-modal-textarea').val(text);
		$('#task-status-select').val($(this).attr('data-status')).trigger('change');
		$('.btn-modal').click();
	});

	$('.save').on('click',function(){
		$.ajax({
			method: 'POST',
			url:'/admin/tasks/edit',
			data:{
				id: $('#id-modal-input').val(),
				text: $('#text-modal-textarea').val(),
				status: $('#task-status-select').val(),
			}
		}).done(function(data){
			$('#text-'+data.id).text(data.text);
			$('#status-'+data.id).text(data.status.text);
			$('.close').click()
		});
	});
JS;

$this->registerJs( $js, $position = yii\web\View::POS_READY, $key = null );
?>

modules/admin/views/users/index.php
<?php


?>
 
<diV class="col-md-12">
	<table class="table table-bordered">
		<caption>Users</caption>
		<thead>
			<tr>
				<th>Id</th>
				<th>Name</th>
				<th>Username</th>
				<th>Role</th>
				<th class="text-right">Control</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($users as $user): ?>
			<tr>
				<td><?= $user->id ?></td>
				<td><?= $user->name ?></td>
				<td><?= $user->username ?></td>
				<td><?= $user->role_id ?></td>
				<td class="text-right" width="15%">
					<a class="btn btn-info">Edit</a>
					<a class="btn btn-danger">Delete</a>
				</td>
			</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</diV>